version: '3'
services:
  app:
    build:
      context: ./docker/app
    volumes:
      - ./html:/var/www/html
    ports:
      - 80:80
    environment:
      TZ: Asia/Tokyo
      VIRTUAL_HOST: promise-all.yuzucloud.net
      LETSENCRYPT_HOST: promise-all.yuzucloud.net
      LETSENCRYPT_EMAIL: studysteadystandby@gmail.com
networks:
  default:
    external:
      name: nginx-proxy
